name: Build and Publish
run-name: Build and Publish (${{ github.ref }}) ${{ inputs.dry_run && '(🧪 Dry-Run)' || '' }}

on:
  push:
    tags:
      - v*
  release:
    types: [published, released]

  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run"
        type: boolean
        default: true
      build_items:
        description: "Build items"
        type: string
        default: "binary,docker"
      tag:
        description: "Tag"
        type: string

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  # Get the current tag
  get_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.tag }}
    steps:
      - name: Get tag
        id: get_tag
        run: |
          if [ "${{ inputs.tag }}" != "" ]; then
            echo "tag=${{ inputs.tag }}" >> $GITHUB_OUTPUT
          elif [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "No tag specified and not triggered by tag"
            exit 1
          fi

  # Build the Docker image
  docker:
    needs: get_tag
    if: inputs.build_items == '' || contains(inputs.build_items, 'docker')
    uses: ./.github/workflows/build-docker.yml
    with:
      version: ${{ needs.get_tag.outputs.tag }}
      dry_run: ${{ inputs.dry_run || false }}
    secrets: inherit

  # Build the binary app
  binary:
    needs: get_tag
    if: inputs.build_items == '' || contains(inputs.build_items, 'binary')
    uses: ./.github/workflows/build-binary.yml
    with:
      version: ${{ needs.get_tag.outputs.tag }}
      dry_run: ${{ inputs.dry_run || false }}
    secrets: inherit
