name: Run Tests

on:
  workflow_call:
  push:
    branches-ignore: ["release/*", "nightly"]
    tags-ignore: ["v*"]
  pull_request:
    branches-ignore: ["release/*", "nightly"]

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '~1.22'

    - name: Run vet
      run: go vet ./...

    - name: Run staticcheck
      uses: dominikh/staticcheck-action@v1
      with:
        version: "latest"

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      continue-on-error: true
      with:
        version: v1.60

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '~1.22'

    - name: Run tests
      run: go test -v ./...
